feign:
  client.config:
    default:
      connectTimeout: 3000
      readTimeout: 3000
      loggerLevel: full
      decode404: false
      errorDecoder: com.polarbear.feigndemo.config.infra.feign.ExceptionHandlingFeignErrorDecoder
      followRedirects: false
    user:
      url: http://localhost:10111